"""Render a generated set as JSON-ready data, a Markdown report, or per-track comments."""

from __future__ import annotations

from typing import Any

from setsmith.model.track import Track
from setsmith.scoring.weights import DEFAULT_CONFIG, ScoringConfig
from setsmith.sets.generate import GeneratedSet, SetPosition, bars_to_seconds


def _energy(t: Track) -> str:
    return f"{t.energy:g}" if t.energy is not None else "-"


def set_to_dict(gen: GeneratedSet, name: str) -> dict[str, Any]:
    return {
        "name": name,
        "curve": gen.curve,
        "stats": gen.stats.to_dict(),
        "warnings": gen.warnings,
        "positions": [
            {
                "position": p.index + 1,
                "track": p.track.summary(),
                "target_energy": round(p.target_energy, 2),
                "transition_to_next": p.transition.to_dict() if p.transition else None,
                "alternates": [
                    {
                        "track": alt.track.summary(),
                        "fit": round(alt.fit, 1),
                        "from_previous": alt.into.to_dict() if alt.into else None,
                        "to_next": alt.out_of.to_dict() if alt.out_of else None,
                    }
                    for alt in p.alternates
                ],
            }
            for p in gen.positions
        ],
    }


def summary_line(gen: GeneratedSet) -> str:
    s = gen.stats
    mae = f"{s.curve_mae:.2f}" if s.curve_mae is not None else "n/a"
    return (
        f"{s.track_count} tracks, ~{s.estimated_seconds / 60:.0f} min, "
        f"{s.bpm_min:g}-{s.bpm_max:g} BPM, mean transition {s.mean_transition:.0f} "
        f"(lowest {s.min_transition:.0f}), energy off-curve by {mae} on average"
    )


def style_line(gen: GeneratedSet) -> str:
    """Style fit and transition mix versus the style's target, or "" without a style."""
    s = gen.stats
    if s.style is None:
        return ""
    fit = f"{s.mean_style_fit:.2f}" if s.mean_style_fit is not None else "n/a"
    mix = ", ".join(
        f"{kind} {100 * s.transition_mix.get(kind, 0):.0f}% (style {100 * target:.0f}%)"
        for kind, target in s.style_transition_mix.items()
    )
    return f"Style {s.style}: mean fit {fit}; transitions {mix}"


def _md(text: str) -> str:
    return text.replace("|", "\\|")


def _transition_cell(p: SetPosition) -> str:
    if p.transition is None:
        return "end"
    return f"{p.transition.suggested_type.value} {p.transition.suggested_length_bars} bars"


def render_markdown(gen: GeneratedSet, name: str) -> str:
    lines = [
        f"# {_md(name)}",
        "",
        f"Curve **{gen.curve}**: {summary_line(gen)}.",
        "",
        "Generated by Setsmith. Scores are 0-100; energy is on a 1-10 scale.",
        "",
    ]
    if gen.stats.style is not None:
        lines += [style_line(gen) + ". Style profiles imply no endorsement by the artists.", ""]
    for warning in gen.warnings:
        lines.append(f"> Warning: {warning}")
    if gen.warnings:
        lines.append("")

    lines += [
        "| # | Track | BPM | Key | Energy (target) | Score to next | Transition | Flags |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for p in gen.positions:
        t = p.track
        score = f"{p.transition.total:.0f}" if p.transition else ""
        flags = ", ".join(p.transition.flags) if p.transition else ""
        lines.append(
            f"| {p.index + 1} | {_md(t.display)} | {t.bpm:g} | {t.camelot or '-'} | "
            f"{_energy(t)} ({p.target_energy:.1f}) | {score} | {_transition_cell(p)} | {flags} |"
        )

    lines += ["", "## Transitions", ""]
    for p, nxt in zip(gen.positions, gen.positions[1:], strict=False):
        if p.transition is None:
            continue
        lines.append(
            f"**{p.index + 1} -> {nxt.index + 1}**: {_md(p.track.display)} -> "
            f"{_md(nxt.track.display)} ({p.transition.total:.1f})"
        )
        lines.append("")
        lines.append("```")
        lines.extend(p.transition.explain())
        lines.append("```")
        lines.append("")

    if any(p.alternates for p in gen.positions):
        lines += ["## Alternates", "", "| # | Planned | Alternates |", "|---|---|---|"]
        for p in gen.positions:
            if not p.alternates:
                continue
            alts = "; ".join(
                f"{_md(a.track.display)} ({a.track.bpm:g}, {a.track.camelot or '-'}, "
                f"E{_energy(a.track)})"
                for a in p.alternates
            )
            lines.append(f"| {p.index + 1} | {_md(p.track.display)} | {alts} |")
        lines.append("")
    return "\n".join(lines)


def set_comments(gen: GeneratedSet, name: str) -> dict[str, str]:
    """Comments text per TrackID for --write-comments: position, score and transition to next."""
    n = len(gen.positions)
    out = {}
    for p in gen.positions:
        note = f"[Setsmith {name} #{p.index + 1}/{n}"
        if p.transition:
            note += f" -> {p.transition.total:.0f} {_transition_cell(p)}"
        note += "]"
        out[p.track.id] = f"{note} {p.track.comments}".strip()
    return out


def set_timeline(gen: GeneratedSet, cfg: ScoringConfig = DEFAULT_CONFIG) -> list[dict[str, Any]]:
    """Where each track sits in the set, in seconds: it starts as the previous one's
    suggested transition begins, and plays its full length."""
    out: list[dict[str, Any]] = []
    t = 0.0
    for p in gen.positions:
        duration = p.track.duration_s or cfg.sets.default_track_seconds
        overlap = 0.0
        if p.transition and p.track.bpm:
            overlap = bars_to_seconds(p.transition.suggested_length_bars, p.track.bpm, cfg)
            overlap = min(overlap, duration / 2)
        out.append(
            {
                "position": p.index + 1,
                "start_s": round(t, 1),
                "end_s": round(t + duration, 1),
                "overlap_next_s": round(overlap, 1),
            }
        )
        t += duration - overlap
    return out
